{{- if .Values.ingress.enabled -}}
{{- if eq .Values.ingress.className "traefik" }}
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ include "meetkit.fullname" . }}-headers
  namespace: {{ .Release.Namespace }}
spec:
  headers:
    customRequestHeaders:
      X-Forwarded-Proto: "https"
---
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "meetkit.fullname" . }}
  labels:
    {{- include "meetkit.labels" . | nindent 4 }}
  annotations:
    {{- if .Values.ingress.tls }}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
    {{- if eq .Values.ingress.className "traefik" }}
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-{{ include "meetkit.fullname" . }}-headers@kubernetescrd
    traefik.ingress.kubernetes.io/service.sticky.cookie: "true"
    traefik.ingress.kubernetes.io/service.sticky.cookie.name: "meetkit-sticky"
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
  - hosts:
    - {{ .Values.domain }}
    secretName: {{ include "meetkit.fullname" . }}-tls
  {{- end }}
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      {{- if .Values.auth.oauth.google.enabled }}
      - path: /auth
        pathType: Prefix
        backend:
          service:
            name: {{ include "meetkit.fullname" . }}-oauth
            port:
              number: 80
      {{- end }}
      - path: /xmpp-websocket
        pathType: Prefix
        backend:
          service:
            name: {{ include "meetkit.fullname" . }}-web
            port:
              number: 80
      - path: /http-bind
        pathType: Prefix
        backend:
          service:
            name: {{ include "meetkit.fullname" . }}-web
            port:
              number: 80
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ include "meetkit.fullname" . }}-web
            port:
              number: 80
{{- end }}
